# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/compose/compose-file/

# Here the instructions define your application as two services called "todo-app" and “todo-database”
# The service “todo-app” is built from the Dockerfile in the /app directory,
# and the service “todo-database” uses the official MongoDB image
# from Docker Hub - https://hub.docker.com/_/mongo.
# You can add other services your application may depend on here.

services:
  app:
    build:
      context: ./
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:mysecetpassword@db:5432/home_db
    ports:
      - 4000:4000
      - 13124:13124
    volumes:
      - app_logs:/path/to/your/app/log
    restart: always
    networks:
      - app_bridge
    develop:
      watch:
        - path: ./src/package.json
          action: rebuild
        - path: ./src
          target: /usr/src/app
          action: sync
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    volumes:
      - db:/data/db
      - db_logs:/var/log/postgresql
    restart: always
    networks:
      - app_bridge
    ports:
      - 5432:5432

volumes:
  db:
  db_logs:
  app_logs:

networks:
 app_bridge:

