# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/compose/compose-file/

# Here the instructions define your application as two services called "todo-app" and “todo-database”
# The service “todo-app” is built from the Dockerfile in the /app directory,
# and the service “todo-database” uses the official MongoDB image
# from Docker Hub - https://hub.docker.com/_/mongo.
# You can add other services your application may depend on here.

services:
  todo-app:
    build:
      context: ./
    depends_on:
      - database
    environment:
      DATABASE_URL: postgresql://postgres:mysecetpassword@database:5432/home_db
    ports:
      - 4000:4000
      - 35729:35729
    develop:
      watch:
        - path: ./src/package.json
          action: rebuild
        - path: ./src
          target: /usr/src/app
          action: sync
  database:
    build:
      context: .
      dockerfile: Dockerfile.db
    volumes:
      - database:/data/db
    ports:
      - 5432:5432

volumes:
  database:
